/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataStructures.Course;
import DataStructures.Task;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.UIManager;
import javax.swing.table.TableModel;
import staticClasses.table;

/**
 *
 * @author zeningluo
 */
public class Main extends javax.swing.JFrame {

    ArrayList<Course> Courses;
    ArrayList<Task> dailySchedule;
    private static int courseNum = 0;
    
    public static final int MaxCoursesNum=7;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        Courses = new ArrayList<Course>();
        dailySchedule = new ArrayList<Task>();
    }
    
    public void addCourse(String name){
        Courses.add(new Course(name));
        courseNum++;
    }
    
    
    public void sortTasks(int type) {
       
        
    }    
    
    
    
    
    private void refreshPanels() {
        //get info from combo box;
        int day = 1;
        drawCoursePanel();
//        drawSchedulePanel(day);
    }

    private void drawCoursePanel() {
        // Get Roster Header
        String[] courseHeader = new String[courseNum];
        for(int i =0; i<courseNum;i++){
            courseHeader[i]=Courses.get(i).getCourseName();
        }
        // Get data for table
        String[][] tableData = new String[6][courseHeader.length];
        // Populate table with data
        for (int x = 0; x < tableData[5].length; x++) {
            // Athlete Info
            tableData[1][x] = Courses.get(x).getTask(0).getName();
            tableData[2][x] = Courses.get(x).getTask(1).getName();
            tableData[3][x] = Courses.get(x).getTask(2).getName();
            tableData[4][x] = Courses.get(x).getTask(3).getName();
            tableData[5][x] = Courses.get(x).getTask(4).getName();
        }

        // Create JTable with all our data
        courseTable.setModel( new table(tableData, courseHeader));

        courseTable.getColumnModel().getColumn(0).setMinWidth(100);
        courseTable.getColumnModel().getColumn(1).setMinWidth(25);
        courseTable.getColumnModel().getColumn(2).setMinWidth(100);
    }
    
    // param    day     mon 1, tue 2, .....
    private ArrayList<Task> findTasks(int day){
        ArrayList<Task> dailyTasks = new ArrayList<Task>();
        for (int i=0;i<courseNum;i++){
            for(int j=0;j<5;j++){
                if(Courses.get(i).getTask(j).getWorkingdays().contains(day)){
                    dailyTasks.add(Courses.get(i).getTask(j));
                }
            }
        }
        
        return dailyTasks;
    }
    
    private void drawSchedulePanel(int day) {

        // Get data for table
        ArrayList<Task> dayTask = findTasks(day);
        String[][] scheduleData = new String[dayTask.size()][1];
        String[] scheduleHeader = {"Schedule"};
               
        // Populate table with data
        for (int x = 0; x < dayTask.size(); x++) {
            // Athlete Info
            scheduleData[x][0] = dayTask.get(x).getName();           
            }
    
        // Create JTable with all our data
        scheduleTable.setModel(new table(scheduleData, scheduleHeader));
        scheduleTable.getColumnModel().getColumn(0).setMinWidth(100);
    }
    
    // Set options, look, and feel of   ?????
    private void guiOptions()
    {
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null,
                    ex);
        }        
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        scheduleTable = new javax.swing.JTable();
        chooseDaysCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();
        addCoursesButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totaltimeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        duedaySort = new javax.swing.JRadioButton();
        prioritySort = new javax.swing.JRadioButton();
        timeSort = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Schedule"
            }
        ));
        jScrollPane1.setViewportView(scheduleTable);

        chooseDaysCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        chooseDaysCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chooseDaysComboItemStateChanged(evt);
            }
        });
        chooseDaysCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDaysComboActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose days");

        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Task#", "1", "2", "3", "4", "5", "6", "7"
            }
        ));
        courseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(courseTable);

        addCoursesButton.setText("Add courses");
        addCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCoursesButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Total Time:");

        totaltimeTextField.setText(" ");

        jLabel3.setText("Sort by:");

        buttonGroup1.add(duedaySort);
        duedaySort.setText("Due Day");

        buttonGroup1.add(prioritySort);
        prioritySort.setText("Priority");

        buttonGroup1.add(timeSort);
        timeSort.setText("working time");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(duedaySort))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(prioritySort)
                                .addComponent(timeSort))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCoursesButton))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chooseDaysCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totaltimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chooseDaysCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addCoursesButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(totaltimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(duedaySort))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prioritySort)
                        .addGap(4, 4, 4)
                        .addComponent(timeSort)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseDaysComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDaysComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseDaysComboActionPerformed

    private void chooseDaysComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chooseDaysComboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseDaysComboItemStateChanged

    private void addCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCoursesButtonActionPerformed
        // TODO add your handling code here:
        JDialog dialog = new JDialog(this, true);
        dialog.add(new AddCourses(this));
        dialog.pack();
        dialog.setVisible(true);

        refreshPanels();
        
    }//GEN-LAST:event_addCoursesButtonActionPerformed

    
    
     // click the table to add task to corresponding course.   ||||||||||||||
    
    private void courseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseTableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() > 1) {
            
        int num = courseTable.getSelectedColumn();
        Course course = Courses.get(num);
        // get the panel for user to input;
        JDialog dialog = new JDialog(this, true);
        dialog.add(new addTaskPanel(course));
        dialog.pack();
        dialog.setVisible(true);

        refreshPanels();
        }
    }//GEN-LAST:event_courseTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCoursesButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> chooseDaysCombo;
    private javax.swing.JTable courseTable;
    private javax.swing.JRadioButton duedaySort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton prioritySort;
    private javax.swing.JTable scheduleTable;
    private javax.swing.JRadioButton timeSort;
    private javax.swing.JTextField totaltimeTextField;
    // End of variables declaration//GEN-END:variables

    
}
